main:
  params: [args]
  steps:
    - init:
        assign:
          - student_name: ${default(map.get(args, "nome"), "Luana")}
          - topic_project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - topic_name: "hogwarts-sorting-topic"

    - validate_input:
        switch:
          - condition: ${len(trim(student_name)) == 0}
            raise: "O nome do estudante não pode ser vazio."

    - publish_to_pubsub:
        try:
          call: googleapis.pubsub.v1.projects.topics.publish
          args:
            topic: ${"projects/" + topic_project + "/topics/" + topic_name}
            body:
              messages:
                - data: ${base64.encode(text.encode(student_name))}
          result: pubsub_response
        retry:
          predicate: ${custom_retry_predicate}
          max_retries: 3
          backoff:
            initial_delay: 2
            max_delay: 10
            factor: 2

    - log_success:
        call: sys.log
        args:
          text: ${"Workflow executado com sucesso para o aluno " + student_name}
          severity: "INFO"

    - return_result:
        return:
          status: "SUCCESS"
          student: ${student_name}
          message_id: ${pubsub_response.messageIds[0]}

custom_retry_predicate:
  params: [e]
  steps:
    - check_retry:
        switch:
          - condition: ${e.code == 500 or e.code == 503 or e.code == 429}
            return: true
    - default_return:
        return: false